### ISSUE TITLE
Page-slider broken on first load

### ISSUE THREAD

**Issue by tony19** [jschr/vscodethemes#106]
### Description

The page-slider button does nothing when first opening the site. I notice the console shows:

    /_next/static/commons/main-57832e66e62ce5722976.js:1 Failed to load resource: the server responded with a status of 404 ()

### Steps to reproduce

 1. Open https://vscodethemes.com/ in an incognito window in Chrome
 2. Hover over any of the theme sections to show the right-arrow button on the righthand side.
 3. Click any of the right-arrow buttons.

### What's expected to happen?

No effect

### What actually happens?

The themes row corresponding to the button slides towards the left.

### Environment

 * macOS High Sierra 10.13.5
 * Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by jschr** [comment]
Hey thanks for taking the time to report this.

I'm not able to reproduce this with the same version of chrome. I also see a different bundle URL now so maybe you encountered a hiccup right after deploying a new version.

Could you try again and let me know if you still see any issues?

Thanks

**Comment by tony19** [comment]
Indeed, it works now!
