### ISSUE TITLE
Twitter image broken

### ISSUE THREAD

**Issue by jschr** [jschr/vscodethemes#110]
Twitter doesn't seem to like screenshot.png for some reason.

<img width="516" alt="screen shot 2018-07-23 at 4 37 57 pm" src="https://user-images.githubusercontent.com/1163252/43101659-e15e1050-8e96-11e8-883a-0b95b2c56576.png">

**Comment by Pustur** [comment]
I think it's because it needs a full URL, so you should try with `https://vscodethemes.com/static/screenshot.png`

**Comment by jschr** [comment]
Ah, that makes sense. Thanks I'll try that.

**Comment by jschr** [comment]
Fixed in https://github.com/jschr/vscodethemes/commit/69811929643326c3b4b7f6b0e411ef026d56dd18, thanks.
