### ISSUE TITLE
Preview custom titlebar color

### ISSUE THREAD

**Issue by Yukaii** [jschr/vscodethemes#113]
Since custom titlebar is coming to Windows/Linux, titlebar color could also be rendered 👍

**Comment by jschr** [comment]
Nice! Good catch. I will definitely do this. 

The missing theme variables that need to be synced appear to be `titleBar.activeBackground`  and `titleBar.activeForeground`. 

Just need to figure out what values to use if the theme doesn't provide theme. Maybe the activity bar?

**Comment by Yukaii** [comment]
https://github.com/Microsoft/vscode/blob/1970dd837d446715525578d2fdfee97ceebc1d72/src/vs/workbench/common/theme.ts#L361-L389

It looks like VSCode has some default colors. 😸

**Comment by jschr** [comment]
Yep! You can see how I use them here: https://github.com/jschr/vscodethemes/blob/production/theme-variables/index.ts

I found that for certain variables it looks like vscode will fallback to another variable if set (ie. tab.activeBackground).

I'll have to play around with those defaults to see what looks best.

Thanks for the report and taking the time to dig into the defaults.

**Comment by jschr** [comment]
Added in https://github.com/jschr/vscodethemes/pull/120/commits/3589690dabfa9aca3d1eef00c7faa889ca9740a9. Really happy with the change, thanks for the report :)
