### ISSUE TITLE
Extension Query Parameters

### ISSUE THREAD

**Issue by kenijo** [jschr/vscodethemes#116]
Hi,

I am developing a app that will generate a RSS feed of all the latest extension being published on on the VSCode marketplace.

When I look at your file vscodethemes/backend/jobs/scrapeExtensions.ts, 
I seen that you have a bunch of filters setup:
```javascript
  const query = {
    filters: [
      {
        criteria: [
          // Not sure what this does and doesn't affect results.
          { filterType: 8, value: 'Microsoft.VisualStudio.Code' },
          // Not sure what this does and doesn't affect results.
          { filterType: 10, value: 'target:"Microsoft.VisualStudio.Code"' },
          // Not sure what this does but does filter out records.
          { filterType: 12, value: '5122' },
          { filterType: 5, value: 'Themes' },
        ],
        direction: 2, // Not sure what this does.
        pageSize: 100,
        pageNumber: page,
        sortBy: 4, // Sorts by most downloads.
        sortOrder: 0,
      },
    ],
    flags: 914, // Settings flags to 914 will return the github link.
  }
```
How did you figure those out (how do you know sortBy:4 is equivalent to sort by most downloads)? Do you have a documentation you could point me too?

Thanks for helping me out!

**Comment by jschr** [comment]
I got most of the way just by browsing the marketplace with the Network tab open. You will see what API calls are made when you sort or filter using the website. 

I also [wrote this blog post](https://hackernoon.com/intercepting-http-requests-from-electron-apps-with-postman-6edc011b0c12) which explains how you can find out what API calls the VSCode app are making when you search extensions. 

Hope that helps!

**Comment by kenijo** [comment]
Awesome, thank you very much. I will keep you posted once I'm done developing the app.

**Comment by jschr** [comment]
Np and please do—would love to check it out.

**Comment by kenijo** [comment]
I got my script done, you can check it out here:
https://github.com/kenijo/FeedPiper/blob/master/vscode_marketplace.php

Right now it is part of a broader project called FeedPiper that allow to:
- Turn an HTML page into a RSS feed
- Merge and filter out RSS feeds

**Comment by jschr** [comment]
Awesome! Is this going to be a hosted app? If so I would definitely be open to putting a RSS subscribe link somewhere on the page.
