### ISSUE TITLE
Amethyst Themes are not showing up

### ISSUE THREAD

**Issue by eamodio** [jschr/vscodethemes#117]
My [Amethyst Themes](https://marketplace.visualstudio.com/items?itemName=eamodio.amethyst-theme) are not showing up, and as far as I can tell it meets all the criteria.

**Comment by jschr** [comment]
hey @eamodio, I'm currently not supporting `includes` so `colors` and `tokenColors` need to be provided for each theme. 

Tracking here: https://github.com/jschr/vscodethemes/issues/118

**Comment by eamodio** [comment]
@jschr Ah, makes sense, thank you! Awesome site/tool btw!

**Comment by jschr** [comment]
Thanks! Right back at ya with gitlens :-) 

Includes should be straight forward to support so I'll likely tackle that in the next round of updates.

**Comment by jschr** [comment]
Added support for includes and your theme now show up on the site: https://vscodethemes.com/e/eamodio.amethyst-theme

**Comment by eamodio** [comment]
Hot damn -- looks awesome, thanks!
