### ISSUE TITLE
Some token colors not rendering correctly

### ISSUE THREAD

**Issue by sheafitzek** [jschr/vscodethemes#125]
This is more of an FYI than an urgent issue. The preview for my [theme](https://marketplace.visualstudio.com/items?itemName=sheafitzek.fitz-dark-italic-vscode-theme) has a few token colors that are off:

- line 1 `document`
	- TM Scope: `support.type`
	- renders: `#ff1111`
	- should be: `#f39c12` `bold`
	- note: the top level `support` token in my theme is `#ff1111` for my own debugging purposes

- line 5 `innerText`
	- TM Scope: `meta.property.object.js`
	- renders: `#f39c12`
	- should be: `#fcf270`
	- note: `#f39c12` is used in my theme, most notably for `storage.type` and `variable.other` scopes

- line 5 `${` and `}`
	- TM Scope: `keyword.other`
	- renders: `#20df20`
	- should be: `#00ffff`
	- note: `#20df20` is used in my theme, most notably for top level `punctuation` and `meta.brace` scopes, `#00ffff` is used for `keyword.other` and `punctuation.definition.variable`

**Comment by jschr** [comment]
![untitled](https://user-images.githubusercontent.com/1163252/43357900-1346d9bc-9257-11e8-8154-0f5fd63c3f86.png)

The left side is what I see in VSCode after installing your extension, the right side is VSCodeThemes.

The only discrepancy I see is in `render()` call.

Do you have some other extensions installed that modify the syntax highlighting?

**Comment by sheafitzek** [comment]
You were right. Turns out it was [Sublime Babel](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode), which adds extra token definitions. It's been installed so long, I forgot it was there.

**Comment by jschr** [comment]
Thanks for confirming. Going to close this for now. The discrepancy in the `render()` call is something I might dig into if it's a more widespread issue.
