### ISSUE TITLE
Theme mixer / builder

### ISSUE THREAD

**Issue by Yukaii** [jschr/vscodethemes#128]
In Sublime or Atom, there are syntax highlight theme and ui theme. In VSCode there is only one. So we can't configure light ui theme with dark syntax directly, only one that theme author published (or you need to customize it manually).

We can extract UI colors, show mixed theme preview, and let user copy & paste colors to their setting. (even making an editor plugin to make pasting color to setting simpler)

But after all this should be done in VSCode. This solution is not quite good 😓

**Comment by jschr** [comment]
I like the idea of adding more value to the site beyond just previews. Being able to edit and create themes to download is an interesting idea—thanks for putting this together.

**Comment by jschr** [comment]
Closing for now. Will consider a feature like this if there's more interest.
