### ISSUE TITLE
Display a notification icon in the previews

### ISSUE THREAD

**Issue by Dan503** [jschr/vscodethemes#131]
I was looking through the previews and thought, this "Dracular" theme looks pretty good.

I downloaded it and gave it a try but then I noticed a fatal flaw in it.

![theme notification badges](https://user-images.githubusercontent.com/10610368/43686220-5481b3b6-9905-11e8-8aca-5a0089373aa6.png)

I could barely read the badge numbers!

It would be nice if the preview screens displayed a notification badge so that we know what the notification badge looks like on each theme.

**Comment by jschr** [comment]
Thanks for the feedback. I agree, that should be part of the preview.

**Comment by jschr** [comment]
Closing for now. Don't have any plans to do this in the near future but may consider if there's more interest.
