### ISSUE TITLE
Old themes are showing up

### ISSUE THREAD

**Issue by tobiastimm** [jschr/vscodethemes#140]
I recognized on my theme https://vscodethemes.com/e/TobiasTimm.raiju that old themes are still showing up. I've removed all variants except `Raiju` and `Raiju - Next`

**Comment by jschr** [comment]
Hey sorry—I totally missed this issue.

I just deleted your old themes (unfortunately this is a manual process right now) and you should see vscodethemes.com update over the next 8-12 hours with them removed. 

Thanks for reporting, I'll have to figure out how to detect deleted themes at some point! 

PS. Raiju is one of up favourites :-)

**Comment by that70schris** [comment]
@jschr can you remove mine from the site?  I've since changed the ID and that's causing some issues so I want to start over.  I've unpublished from vscode marketplace for now

**Comment by jschr** [comment]
Sure thing @that70schris , would you mind opening a separate issue so I don't forget? Thanks
