### ISSUE TITLE
Server rejecting connection with 500

### ISSUE THREAD

**Issue by KasiMaru** [jschr/vscodethemes#148]
Getting "Oops! Something went wrong." on frontend and "Operations quota exceeded, change plan to get more Operations" in console. Apparently this is a problem of Algolia free plan and there is nothing you can do (except for paying them), but you should know this is happening anyway. 

Also, thanks for the very useful service!

**Comment by jschr** [comment]
Hey @KasiMaru, sorry just saw this but I did get all the alarm notifications when it broke :-) 

I ended up upgrading to a paid one. I was on the open source plane but it doesn't include enough operations. This unfortunately limits my ability to build certain features like #59 so I've been thinking about a backend rewrite to address this but will take some time.

Thanks for reporting!
