### ISSUE TITLE
An old theme version is showing up

### ISSUE THREAD

**Issue by MatiasOlivera** [jschr/vscodethemes#152]
I've noticed that an older version of my theme [Universe](https://vscodethemes.com/e/MatiasOlivera.universe) is still showing up on the page. The version with the yellow icons is no longer included in the latest releases.

Nice work, I love the website!

---

Related with #140

**Comment by jschr** [comment]
Thanks! I just removed the old theme. Unfortunately, it's a manual process right now. I'm working on a new version that will solve this and many other problems I'm having with the current version :-)

**Comment by jschr** [comment]
Side note: If you have any ideas for the new site please feel free to suggest them! I'd love to hear from theme authors if there are any missing features or nice-to-haves.

**Comment by MatiasOlivera** [comment]
Thank you @jschr!
