### ISSUE TITLE
text flicker on hover

### ISSUE THREAD

**Issue by dsmmcken** [jschr/vscodethemes#163]
![Jan-16-2020 14-10-04](https://user-images.githubusercontent.com/1576283/72556661-1699f280-386d-11ea-96a6-42cbc2a90dc4.gif)

Specific to non-catelina macs, in chrome, and maybe other os/browser combos where the svg text is sub-pixel anti-aliased. You can see it flicker when the button appears on hover over a theme (particularly on the bolded text like const). This is a compositing issue during the opacity animation.

I suggest setting `will-transform: opacity, transform;` on the animating button, to hint to the browser to not composite over the svg text, and do it in a different layer, to eliminate the flicker and possibility give negligibly better performance.

**Comment by jschr** [comment]
Fixed in https://github.com/jschr/vscodethemes/pull/177/commits/cd05078ea741cf69d8a9c7f38ca4bb72ca3164ab
