### ISSUE TITLE
Theme not appearing: Yarra Valley

### ISSUE THREAD

**Issue by dustypomerleau** [jschr/vscodethemes#168]
Outstanding work putting together this site–would be grateful for any help making my theme appear. I believe it meets all criteria in the README. Theme name is [Yarra Valley](https://marketplace.visualstudio.com/items?itemName=dustypomerleau.yarra-valley).

**Comment by jschr** [comment]
hey @dustypomerleau, looks like your theme is up now: https://vscodethemes.com/e/dustypomerleau.yarra-valley

It can take up to 24 hours for updates to appear on the site.

**Comment by dustypomerleau** [comment]
Great - Thank you for your time, @jschr.
