### ISSUE TITLE
Remove Arcade theme from the site

### ISSUE THREAD

**Issue by that70schris** [jschr/vscodethemes#169]
can you remove mine from the site? I've since changed the ID and that's causing some issues so I want to start over. I've unpublished from vscode marketplace for now

https://vscodethemes.com/e/that70schris.arcade

**Comment by that70schris** [comment]
current id: 'arcade'
current name: '🕹 Arcade'

maybe just remove the other variants to keep the numbers in tact?

**Comment by jschr** [comment]
Hey @that70schris, can you clarify which theme you want removed?

Do you want to keep '🕹 Arcade' and remove 'Arcade'?

**Comment by that70schris** [comment]
yea, keep '🕹 Arcade' and remove 'Arcade'

**Comment by jschr** [comment]
Removed

**Comment by that70schris** [comment]
Awesome! thank you!

**Comment by that70schris** [comment]
hey sorry to bother you again, it seems like there are once again 2 variants, this time they both have the same name but different numbers.  Not sure if it's possible to clean this up.

just for reference, here is may package.json

```
{
  "author": {
    "email": "chris@bailey.codes",
    "name": "Chris Bailey",
    "url": "https://bailey.codes"
  },
  "categories": [
    "Themes"
  ],
  "contributes": {
    "grammars": [
      {
        "injectTo": [
          "source.css"
        ],
        "path": "./dist/css.json",
        "scopeName": "injection.css"
      },
      {
        "injectTo": [
          "source.nginx"
        ],
        "path": "./dist/nginx.json",
        "scopeName": "injection.nginx"
      }
    ],
    "themes": [
      {
        "id": "arcade",
        "label": "🕹 Arcade",
        "path": "./themes/Arcade.color-theme.json",
        "uiTheme": "vs-dark"
      }
    ]
  },
  "description": "Somewhere between neon and pastel",
  "devDependencies": {
    "@types/css": "0.0.31",
    "@types/node": "13.9.1",
    "@types/plist": "3.0.2",
    "@typescript-eslint/eslint-plugin": "2.24.0",
    "@typescript-eslint/experimental-utils": "2.24.0",
    "@typescript-eslint/parser": "2.24.0",
    "css": "2.2.4",
    "eslint": "6.8.0",
    "husky": "4.2.3",
    "lint-staged": "10.0.8",
    "plist": "3.0.1",
    "prettier": "1.19.1",
    "sass": "1.26.3",
    "stylelint": "13.2.1",
    "stylelint-order": "4.0.0",
    "stylelint-prettier": "1.1.2",
    "stylelint-scss": "3.15.0",
    "ts-node": "8.6.2",
    "typescript": "3.8.3",
    "vsce": "1.74.0"
  },
  "displayName": "🕹 Arcade",
  "engines": {
    "vscode": "^1.36.0"
  },
  "name": "arcade",
  "publisher": "that70schris",
  "repository": {
    "type": "git",
    "url": "https://github.com/that70schris/arcade"
  },
  "version": "0.16.3"
}
```

**Comment by jschr** [comment]
Each theme is keyed on `{publisher}${extension}${path-to-theme.json}`. For example `that70schris$arcade$dist/arcade.json`

Looks like at some point you moved the themes from `dist` to `themes` so the old `dist` themes are still kicking around. I'm working on the next version of vscodethemes that will be able to automatically delete themes. For now just keep opening issues and I'll do it manually.

I've removed the duplicate.

**Comment by that70schris** [comment]
ohhh, gotcha.  one of my machines still had the dist file.  hopefully now that it's deleted it won't happen again.

That's pretty cool! are you starting over from scratch?  If you need any FE help let me know.

Thanks again!

**Comment by jschr** [comment]
Not entirely from scratch, I'll be ripping apart the backend to support more languages and cleaning themes automatically. That'll be the biggest chunk but I hope to tackle some features on the frontend too. 

If you have any suggestions for features or feedback on any of the open feature requests feel free to contribute!
