### ISSUE TITLE
A couple variations of Tokyo Night isn't showing up

### ISSUE THREAD

**Issue by enkia** [jschr/vscodethemes#172]
Only one variation (Storm) of [Tokyo Night](https://marketplace.visualstudio.com/items?itemName=enkia.tokyo-night) is showing up in lists. Is there anything I need to modify to fix this?

**Comment by jschr** [comment]
Looks like there's 2/3 themes there now, still missing Tokyo Theme Light. I had to slow down the sync to once a week to minimize costs so it might not have picked up your latest changes yet. I'll keep eye on it for the next coupe days.

**Comment by jschr** [comment]
Looks like all 3 are up now, it just took a while.

**Comment by enkia** [comment]
Thanks for looking into it. Although when I do a search for 'Tokyo', I just see the one (Tokyo Night Storm, my favorite incidentally) and two others with 'Tokyo' in their names.

**Comment by jschr** [comment]
Only one theme will show up per extension because some extensions have hundreds of themes and dominated the pages. I'll probably change that though and limit the amount of themes per extension instead.
