### ISSUE TITLE
Theme not showing up

### ISSUE THREAD

**Issue by AlvaroIsrael** [jschr/vscodethemes#174]
Hello congratulations for this project really amazing.
I have a VSCode theme (Monokai Dark Green) and I'm not sure why is not showing up on VSCodeThemes.com

I believe they match the criteria for showing up. I appreciate your help.

Marketplace Link: https://marketplace.visualstudio.com/items?itemName=alvaro-israel-nunes-leite.theme-monokai-dark-green

GitHub Link: https://github.com/AlvaroIsrael/monokai-dark-green

**Comment by jschr** [comment]
It can take up to a week for a new theme to show up. 

I'll check back in a few days. 

https://vscodethemes.com/e/alvaro-israel-nunes-leite.theme-monokai-dark-green

**Comment by jschr** [comment]
Sorry for the delay. There appears to be an issue preventing some themes from syncing. I'm looking into it.

**Comment by AlvaroIsrael** [comment]
Thanks for your support. I'll wait for your fix!

**Comment by jschr** [comment]
hey @AlvaroIsrael, your theme is up on the site now: https://vscodethemes.com/e/alvaro-israel-nunes-leite.theme-monokai-dark-green

**Comment by AlvaroIsrael** [comment]
Thank you very much!
