### ISSUE TITLE
My theme is not showing up

### ISSUE THREAD

**Issue by Jean-Tinland** [jschr/vscodethemes#178]
Hi,

I may need help with my theme which is not showing up on your website.

My theme was published on the market place ([here](https://marketplace.visualstudio.com/items?itemName=jean.desaturated)) on 30/04/2020 and my themes are well declared in the contributes fields of my package.json.

Am I missing something?

Thank you for your help.

_Edit: [git repo is accessible here](https://github.com/Jean-Tinland/vscode-theme-desaturated)._

**Comment by jschr** [comment]
Hey, I manually pushed your theme to the site: https://vscodethemes.com/e/jean.desaturated 

I recently pushed a fix for themes not syncing and I think things are still catching up, might take a few more before the site is fully updated.

**Comment by JeanTinland** [comment]
Okay, thank you very much for your help!
