### ISSUE TITLE
Theme is not showing up

### ISSUE THREAD

**Issue by mubartok** [jschr/vscodethemes#184]
Hello, I always came here to find new themes I liked and today I created mine 🎉 but it doesn't show up.
Maybe it's just a matter of time but because I read in the other issues that you sometimes had to push them manually, I open this issue just in case.

https://github.com/mubartok/minuit-vscode-theme
https://marketplace.visualstudio.com/items?itemName=mubartok.minuit

Thanks in advance for your help!

**Comment by Pustur** [comment]
@mubartok Seems like your theme is now showing up, very nice theme btw!

**Comment by mubartok** [comment]
Thank you!

**Comment by mubartok** [comment]
Thank you! 🙂
