### ISSUE TITLE
Subject to find

### ISSUE THREAD

**Issue by jahnli** [jschr/vscodethemes#188]
[Uploading grey_orange.zip…]()

Is there such a theme or can it be made

![image](https://user-images.githubusercontent.com/20943608/95711164-cc775d80-0c94-11eb-94e4-e7c2a69f80f3.png)

![image](https://user-images.githubusercontent.com/20943608/95711155-c71a1300-0c94-11eb-8090-008d6abbac8f.png)

**Comment by jschr** [comment]
https://code.visualstudio.com/api/extension-guides/color-theme#create-a-new-color-theme
