### ISSUE TITLE
My theme is not showing up

### ISSUE THREAD

**Issue by EricsonWillians** [jschr/vscodethemes#193]
Hi,

I've followed the instructions here and my theme is not showing up, I think it must be added manually.

Github: https://github.com/EricsonWillians/oldschool-theme
VSCode Marketplace: https://marketplace.visualstudio.com/items?itemName=EricsonWillians.oldschool-theme

Thanks!

**Comment by jschr** [comment]
Looks like it got added: https://vscodethemes.com/e/EricsonWillians.oldschool-theme

It can take a few days for theme updates to show up on the site.
