### ISSUE TITLE
Extension includes multiple themes but only the first is indexed

### ISSUE THREAD

**Issue by dfoxfranke** [jschr/vscodethemes#195]
My [Lunaria](https://marketplace.visualstudio.com/items?itemName=dfoxfranke.lunaria) extension includes one light and two dark themes, but only the light theme appears on vscodethemes.com.

**Comment by jschr** [comment]
https://vscodethemes.com/e/dfoxfranke.lunaria

Looks like it's showing all 3 now. It can take a few days for theme updates to apply.
