### ISSUE TITLE
new theme

### ISSUE THREAD

**Issue by Tyh2001** [jschr/vscodethemes#218]
# hello

I recently developed a new vscode theme. Can I put it on the website?
My theme is here：https://github.com/Tyh2001/tyh-theme-vscode

Look forward to your reply

tyh2001

**Comment by jschr** [comment]
Your theme appears to be on the site not: https://vscodethemes.com/e/tyh-theme.tyh-theme 

I had hit some limits and was being throttled so it took a while.

**Comment by Tyh2001** [comment]
thank～
