### ISSUE TITLE
Other color for comments in .tpl files

### ISSUE THREAD

**Issue by vellkan** [jschr/vscodethemes#219]
Hello!

It is possible to add new definition for comments color in tpl files?
I mean comments like:
{* comment
* comment
* comment
*}
Now it's look like HTML text and sometimes (during editing Prestashop themes) it is distracting.

**Comment by jschr** [comment]
Hey, if you are looking to make a feature request to vscode you might start with the vscode repo: https://github.com/microsoft/vscode/

All this website does it display themes from the marketplace.

Sorry if I misunderstood your request. Please provide more information if I did. Thanks.
