### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by jschr** [jschr/vscodethemes#70]
One extension / repo can have many themes. This causes one author / repo to take over many pages.

- Is this actually a problem?
- How can we present a group of themes in the search while maintaining discover-ability?

https://www.algolia.com/doc/guides/ranking/distinct/?language=javascript#distinct-for-grouping

**Comment by albertorestifo** [comment]
I think this is a problem. Rainglow for example, will span on many pages.

What about showing a group as "stacked cards" that you can expand to reveal all the variants?

**Comment by jschr** [comment]
@albertorestifo Spot on, that's exactly what I was thinking too. I'll be addressing this in #88. Appreciate the feedback, let me know if you think of anything else.

**Comment by jschr** [comment]
Closing. Will be resolved in https://github.com/jschr/vscodethemes/pull/88
