### ISSUE TITLE
Wasted space

### ISSUE THREAD

**Issue by Splike** [jschr/vscodethemes#82]
There is a lot of wasted space on the page. It would be nice if the grid of themes would change with the windows size, so a lot more space can be utilized and a lot more themes can be shown per page.

**Comment by jschr** [comment]
Hey, thanks for the feedback! It was a challenge to get everything to look right on mobile and resulted in a design that appealed to the lowest-common denominator. 

My priority has been getting the syntax highlighting to actually be accurate. I've just about got that solved after which I plan to focus on the front-end. 

I've got some really cool features planned so stay tuned :-)

**Comment by jschr** [comment]
Closing. Will be resolved in https://github.com/jschr/vscodethemes/issues/75
