### ISSUE TITLE
Download source from the marketplace

### ISSUE THREAD

**Issue by jschr** [jschr/vscodethemes#93]
If we can download the extension source directly from the marketplace we can remove the github dependency and don't need to support different repo setups.

**Comment by jschr** [comment]
Hey @Tyriar—hope you don't mind the ping.

Wondering if you might be able to point me in a direction with this one. In order to get the theme definition I require that published themes specify a public github repo. 

I'm also relying on a particular repo structure so I also can't support certain setups like yarn workspaces or repos that have a build step before publish.

Is there a more direct way to extract the theme definitions from an extension?

**Comment by Tyriar** [comment]
Extensions have a download link on the right side bar, I guess you could use that link, note that the endpoint might change in the future, a different team runs the marketplace:

<img width="172" alt="screen shot 2018-07-25 at 6 29 23 am" src="https://user-images.githubusercontent.com/2193314/43203870-38c63726-8fd4-11e8-8ed7-54c377a6fdd6.png">

The link doesn't seem to work on Linux but it does on macOS, following that up now.

**Comment by Tyriar** [comment]
Related: https://code.visualstudio.com/docs/editor/extension-gallery#_can-i-download-an-extension-directly-from-the-marketplace

**Comment by jschr** [comment]
Awesome, much appreciated!
